### ISSUE TITLE
Milestone: Beta Launch (due Sep 1, 2018)

### ISSUE THREAD

**Issue by mnkykm** [glossm/api#47]
베타 런칭을 9월 1일을 목표로 합니다. 베타 사이트에서는 다음과 같은 기능이 완전히 구현되기를 희망합니다. 

1. 5개 언어 과정 제공 
2. 언어 자료의 어휘, 문법, 회화 항목 중 어휘 항목 구현 
3. 언어 과정 내에 게임 세션 (듣고 전사하기) 와 복습 세션 (전사 보고 뜻 맞히기) 구현 
4. IPA 입력기 및 튜토리얼 과정 
5. 브랜딩 및 PR 자료

**Comment by mnkykm** [comment]
해결 우선 순위

- Technical issues
- [ ] #23 Upstream prematurely closed connection error
- [ ] #11 Setup continuous integration
- [ ] #38 Move to Amazon RDS
- Models
- [ ] #39 Multiple records corresponding to the same meaning (Informant Model 추가)
- [ ] #43 Divide Language into Courses
- [ ] #42 Mass upload of records

_(Last Updated: June 24, 2018)_
